name: "My custom action"
description: "Run a python script"
inputs:
  directories:
    required: true
    description: "Input directories to crawl"
runs:
  using: "docker"
  image: Dockerfile
  args:
    - ${{ inputs.directories }}
