on:
  push:
  workflow_call:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zsol/action-playground@v2
        with:
          directories: example_inputHELLO
